spring.application.name=previsao_do_clima
# CONFIGURAÇÕES DO BANCO MYSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/obj_smart_clima
spring.datasource.username=postgres
spring.datasource.password=#Leticia328
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# CHAVES DE API
openweathermap.api.key=e29c5c1ea215ccb97edc2a28687be557
gemini.api.key=AIzaSyBLyNpHfwnqsJ43Tu1IlztloMss0ZHdTuk

# SWAGGER CONFIG
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html